apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-app-k8s
  labels:
    app: my-app-k8s
spec:
  replicas: 3
  selector:
    matchLabels:
      app: my-app-k8s
  template:
    metadata:
      labels:
        app: my-app-k8s
    spec:
      containers:
      - name: my-flask-app
        image: my_app:lts
        ports:
        - containerPort: 8000
