apiVersion: v1
kind: Service
metadata:
  name: my-app-k8s-service
spec:
  type: LoadBalancer  # Use 'NodePort' or 'ClusterIP' as needed
  ports:
  - port: 8000          # Port that will be exposed to the outside
    targetPort: 8080  # Port your Flask app listens on
  selector:
    app: my-app-k8s
